spring:
  profiles:
    - default
    - dev
  datasource:
    url: jdbc:mysql://localhost:3306/thaz?useUnicode=yes&characterEncoding=UTF-8
    username: thaz
    password: KkN7{/uvw}?CKi).hDY8YSM0}YMC3QT
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #                dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
